### ISSUE TITLE
support for Payum 0.12

### ISSUE THREAD

**Issue by informatico-madrid** [crevillo/payum-redsys#19]
Hi, I do not have much experience in Payum. But I need Redsys gateway in Payum 0.12 to implement in Sylius. Not if you could tell me what changes are needed. Thank You.

Hola, No tengo mucha experiencia en Payum. Pero necesito redsys gateway en Payum 0.12 para implementar en Sylius. No se si podrías indicarme que cambios son necesarios. Gracias.

**Comment by crevillo** [comment]
Hola, Tengo en mente integrarlo con sylius, pero no he tenido tiempo ahora. en todo caso yo con payum estoy trabajando con la 0.13...

**Comment by makasim** [comment]
I am going to release Payum 0.14 soon and make this merged https://github.com/Sylius/Sylius/pull/2384

**Comment by crevillo** [comment]
great @makasim. ping to tag redsys :).

**Comment by informatico-madrid** [comment]
Genial!!. Voy a probar lo y ver si saco yo tiempo para integrar con sylius. Gracias de nuevo.

Great !!. I'll try it and see if I have time to integrate it in Sylius. Thanks again.

**Comment by informatico-madrid** [comment]
Sorry for the newbie question. How I can use your Fork in Composer? I tried to replace your Fork in sylius composer, but Composer can not find it. I tried to add in your fork composer as a repository, but composer deletes all dependencies required to sylius.

Perdona por la pregunta de novato. Como puedo usar tu Fork en Composer? He intentado remplazar sylius con tu FOrk en composer, pero Composer no lo encuentra. He intentado añadir en composer tu fork como un repositorio, pero composer borra todas las dependencias requeridas de sylius.

**Comment by makasim** [comment]
In the repositories section of your composer.json file you have  put your repo and change the version of the lib like this `dev-{branch-name}`

```json
{
  "require": {
    "crevillo/payum-redsys": "dev-compatible-with-012 as 0.12.0"
  },
  "repositories": [
       {
          "type": "vcs"
          ,"url": "git@github.com:informatico-madrid/payum-redsys.git"
        }
   ]
}
```

after that you can do `php composer update crevillo/payum-redsys`

**Comment by informatico-madrid** [comment]
Gracias. pero por ahora primero quiero usar https://github.com/Sylius/Sylius/pull/2384 como fork de Sylius(He creado mi propio fork para esto) y después incorporar Crevillo/payum-Redsys. Según indicas tengo esto en Composer:

Thank You. but for now I want to use first https://github.com/Sylius/Sylius/pull/2384 as Sylius fork(I create a fork of your fork for this) and then enter Crevillo / payum-Redsys. According you note I have this in Composer:
"repositories": [
   {
     "type": "vcs",
     "url": "git@github.com:informatico-madrid/Sylius.git"
    }
],
"require": {
        "informatico-madrid/Sylius":            "dev-configure-payments-in-backend-v2",
    },
`
También he intentado con éste Require:

I've also tried it Require:
`
"require": {
        "informatico-madrid/Sylius":            "dev-configure-payments-in-backend-v2@dev",
    },
`
pero todavía tengo un error en Composer, pero esta vez diferente:
but still I have an error in Composer, but this time different:
>Problem 1
>    - The requested package informatico-madrid/sylius could not be found in any version, there may >be a typo in the package name.
>Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability >setting
>   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Como puedo hacer para que Composer encuentre el nombre de la rama?
How I can do to make Composer find the name of the branch?

**Comment by informatico-madrid** [comment]
Thankx makaxim for dev-configure-payments-in-backend-v2 marge in sylius.
I implement Crevillo/payum-redsys in sylius with this.
First: I have extend SyliusWebBundle With my own bundle: AcmeWebBundle
```
<?php

namespace Goprofit\Wainari\WebBundle;

use Payum\Bundle\PayumBundle\DependencyInjection\Compiler\BuildPaymentFactoryPass;
use Payum\Bundle\PayumBundle\DependencyInjection\Compiler\BuildRegistryPass;
use Symfony\Component\HttpKernel\Bundle\Bundle;
use Symfony\Component\DependencyInjection\ContainerBuilder;

use Crevillo\Payum\Redsys\Bridge\Symfony\RedsysPaymentFactory;

class GoprofitWainariWebBundle extends Bundle
{

    public function build(ContainerBuilder $container)
    {
        parent::build($container);

        /** @var $extension DependencyInjection\PayumExtension */
        $extension = $container->getExtension('payum');

        
        $extension->addPaymentFactory(new RedsysPaymentFactory);

    }
}
```
And i add a config for payum in my app/config.yml
```
payum:
    payments:
        transfer:
            custom:
                actions:
                    - goprofit_wainari.payum.transfer.action.capture_payment
                    - goprofit_wainari.payum.transfer.action.payment_status
        redsys:
            redsys:
                merchant_code: 00000000 
                terminal: 1
                secret_key: xxxxxxxxxx0000000000
                sandbox: true          
```
But i cant get yet work a notify url to update shop inventary.
