### ISSUE TITLE
Why don't you mark the payment as captured in the NotifyAction?

### ISSUE THREAD

**Issue by jdeveloper** [crevillo/payum-redsys#23]
Just a little question

In the NotifyAction, you just check if the signature is valid. The problem I see is that in fact in this siguation you could verfy if the payment was realized (credit card was accepted) by executing a GetStatus. 

At now, if after I entered the credit card, in the next step, if I close the window instead of pressing the "Continue" button, I would have my payment as pending when in reality I payed,

**Comment by makasim** [comment]
It is not only checks the signature but [updates payment details](https://github.com/crevillo/payum-redsys/blob/master/Action/NotifyAction.php#L52).

You have to add a payum extension which checks the payment status and dispatch an event or do any other actions.

**Comment by makasim** [comment]
Here's an example of how the extension may look like: http://payum.org/doc/1.0/Core/instant-payment-notification
