### ISSUE TITLE
Function mcrypt_encrypt() is deprecated in PHP 7.1

### ISSUE THREAD

**Issue by gtrias** [crevillo/payum-redsys#30]
The function mcrypt_encrypt is deprecated in PHP7.1.

It is used in Crevillo/Payum/Redsys/Api.php line 171. I'm not sure how it should be replaced.
I think it should be replaced by `openssl_encrypt()`. But I'm not sure if it will affect in the Bundle working in some way.

More info: 
- http://php.net/manual/en/function.mcrypt-encrypt.php
- http://php.net/manual/en/migration71.deprecated.php

**Comment by crevillo** [comment]
good catch!. thanks a lot. i'll try to have a look to this during next weekend. prs are welcome btw! :)

**Comment by carmenates09** [comment]
This solution was by @dataclickes  on https://github.com/eusonlito/redsys-TPV/issues/14 meaby it help you to fix that.

```
function encrypt_3DES($message, $key) {

     $l = ceil(strlen($message) / 8) * 8;
    return substr(openssl_encrypt($message . str_repeat("\0", $l - strlen($message)), 'des-ede3-cbc', $key, OPENSSL_RAW_DATA, "\0\0\0\0\0\0\0\0"), 0, $l);
}
```

Jose Carlos Ramos Carmenates.

**Comment by crevillo** [comment]
Thank you! Feel free to open a pr with this.
