### ISSUE TITLE
Cannot come back to Redsys after cancel

### ISSUE THREAD

**Issue by marcverney** [crevillo/payum-redsys#34]
## Use case

Imagine the following situation: on my website, a customer is sent to Redsys to pay for an order, but once there they click on the Cancel button because they want to pay later. The next time they want to pay for this (same) order, it will be impossible. No redirection to Redsys will be done.

## Explanation

When the Cancel button is clicked in Redsys:

- the customer is returned to my website
- Redsys sends a notification to my website

Payum handles Redsys' notification with its `$gateway->execute(new Notify($token))` process. In payum-redsys' `NotifyAction`, Redsys notification details are [added to the order's `details` fields](https://github.com/crevillo/payum-redsys/blob/master/Action/NotifyAction.php#L63), and later persisted in database. One of those details is `Ds_Signature`.

When the customer comes back to pay for the (same) order, there's no way for them to be redirected to the Redsys gateway, because payum-redsys' `CaptureAction` only redirects [when `Ds_Signature` is falsy](https://github.com/crevillo/payum-redsys/blob/master/Action/CaptureAction.php#L95):

```php
if (false == $postData['Ds_Signature']) {
    $details['Ds_Signature'] = $this->api->sign($postData->toUnsafeArray());

    throw new HttpPostRedirect($this->api->getRedsysUrl(), $details);
}
```
Am I missing something or is there a problem here?

**Comment by crevillo** [comment]
Hi. I see your point and your explanation. but on the other hand, you're saying that you're trying to pay for this order, which i understand, but it doesn't mean necessary that you are using the same "payment". 

In other words, when the user comes back to pay for the order, say, order with id `100` why don't create a new payment for that order? 

You will end probably with a table of payments like, more or less
```
payment_id | order_id | status
1                  | 100        | cancelled by user
2                  | 100        | cancelled by user
3                  | 100        | ok
 ``` 

so, when the user tries to pay again, you create a new payment and at that time Ds_Signature will be false....

Other option could be modify that condition to check for other of the existing values, but to me this is more easy to maintain. Is what Sylius does, btw.

**Comment by marcverney** [comment]
Ooop, I've just realized I never replied here, sorry. Your suggestion to use a payment object instead of leveraging the order directly works. What had confused me is that Redsys treats this object as an order, for example it uses its id to prevent you from paying twice. But anyway, everything works fine, thank you for your help, Carlos.
