### ISSUE TITLE
Error 500 after payment success

### ISSUE THREAD

**Issue by Julen10** [crevillo/payum-redsys#40]
I have patched what @h3llr4iser made for completing the payments.
After that, I´m able to complete the paymet via Redsys and it´s registered as authorized, but on Sylius the order still Pending for payment.

On Redsys panel I can see this:
Error (Server returned HTTP response code: 500 for URL: https://myshopurl.com/payment/notify/zmM6iWVwriknz4d-MU0Ht8xQnKIjzzHfJ1O_G3ixVTY
And Ds_SignatureVersion, Ds_MerchantParameters and Ds_Signature correctly created.

What could be the problem?
Thanks,

@crevillo

**Comment by h3llr4iser** [comment]
Hi,
You soulld review the server logs to see more details about the exception in symfony.
